For 0.5 or later:

    Add service like funcionality for Ubuntu and other flavors of Gnu/Linux
    Ask helix to package for deb.torproject.org.
    autoconf the entire build process for better portability
    make it simple to bump the version number for ttdnsd during release time
        currently, a release requires editing many files:
        Makefile, debian/control, debian/changelog, ttdnsd.h, package/ttdnsd/Makefile

For 0.5 or later:

    re-write ttdnsd to use libevent

